"""Build a 5-fold cross-validation corpus for the fraction-head quadrat-supervised
retrain, extending the original single-holdout experiment
(docs/issues/quadrat-supervision-fraction-retrain.md) to all 27 current Rule-1
quadrats instead of the 13 it had then, and to 5 held-out folds instead of one
(karachi_coast_calib_700m, n=1 -- the doc's own closing line calls out "more holdout
folds, not more analysis" as what would actually settle the question).

Folds are assigned round-robin over quadrats SORTED BY BASE RATE (roofclf's
`data/roofclf/folds.csv`), not by name or size -- so every fold gets a representative
spread from near-zero (nasirabad_rural) to high (islamabad_west) rather than one fold
accidentally drawing all the rural near-zero quadrats or all the dense urban ones.

For each fold, two corpora are filtered to exclude that fold's held-out quadrats,
mirroring exactly how the original karachi_coast holdout closed its two leakage paths
(docs/methods/quadrat-supervision, "TWO leakage paths were closed before training"):

1. **The quadrat corpus itself** (`data/chips/pakistan_quadrat_fraction/index.parquet`,
   rebuilt fresh for all 27 quadrats by `earthpv quadrat-chips --aoi pakistan`,
   2026-08-14) -- trivial, just drop rows whose `quadrat` column is in the held-out set.
2. **The national corpus** (`data/chips/pakistan_fraction/index.parquet`) -- a chip
   here that geographically overlaps a held-out quadrat's boundary would still teach
   the model that exact ground under national (unverified-surroundings) supervision,
   defeating the holdout. Every chip's bbox (`chips._chip_bbox`, the same 2.24 km
   window the corpus was built with) is tested against the held-out boundaries' union.

Each fold's combined training index is written to
`data/chips/combined_fraction_kfold/fold{N}/index.parquet`
(germany_fraction x1, pakistan_fraction_fold{N} x2, quadrat_fraction_fold{N} x8 --
the same ratio `terramind_pv_fraction_pakistan_quadrats.yaml`'s docstring recorded for
the original 13-quadrat run), and a matching config
`configs/terramind_pv_fraction_kfold{N}.yaml` is written alongside it.

**Germany's contribution is smaller here than in that original run** (412 chips, not
5,587): the original corpus's germany rows point at `data/chips_unfiltered/
germany_fraction/images/*.tif`, and that directory no longer exists on disk (checked,
2026-08-14 -- 0/50 sampled files resolve), so those pixels cannot be reused even by
reading them out of the already-merged `combined_fraction_quadrats` index. The current
`data/chips/germany_fraction` (412 chips, files verified present) is the only Germany
fraction-task corpus actually available, and is used as-is rather than left out.

Usage:
    .pixi/envs/default/bin/python scripts/build_fraction_kfold.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import geopandas as gpd
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from earthpv.chips import _chip_bbox  # noqa: E402
from earthpv.roofclf import discover_quadrats, load_boundary, quadrat_label  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
LABELS_DIR = ROOT / "data" / "labels"
CHIPS_DIR = ROOT / "data" / "chips"
FOLD_DIR = CHIPS_DIR / "combined_fraction_kfold"
CONFIG_DIR = ROOT / "configs"
N_FOLDS = 5
GERMANY_REPEAT = 1
PAKISTAN_REPEAT = 2
QUADRAT_REPEAT = 8

CONFIG_TEMPLATE = """\
# TerraTorch fine-tuning config for PV FRACTION regression -- k-fold {fold},
# {n_heldout} quadrats held out ({heldout_labels}). Generated by
# scripts/build_fraction_kfold.py, 2026-08-14 -- see that script's docstring for the
# fold assignment and the two leakage checks. Same recipe as
# configs/terramind_pv_fraction_pakistan_quadrats_holdout_karachi.yaml in every
# respect except the corpus (backbone, necks, decoder, loss, lr, schedule).
task_type: regression

data:
  index_path: data/chips/combined_fraction_kfold/fold{fold}/index.parquet
  batch_size: 8
  num_workers: 4
  target: fraction

task:
  model_factory: EncoderDecoderFactory
  model_args:
    backbone: terramind_v1_tiny
    backbone_pretrained: true
    backbone_modalities: [S2L2A]
    backbone_bands:
      S2L2A: [BLUE, GREEN, RED, RED_EDGE_1, RED_EDGE_2, RED_EDGE_3,
              NIR_BROAD, NIR_NARROW, SWIR_1, SWIR_2]
    necks:
      - name: SelectIndices
        indices: [2, 5, 8, 11]
      - name: ReshapeTokensToImage
        remove_cls_token: false
      - name: LearnedInterpolateToPyramidal
    decoder: UNetDecoder
    decoder_channels: [256, 128, 64, 32]
    head_final_act: torch.nn.Sigmoid
    rescale: true
  loss: weighted_mse
  weighted_mse_args: {{k: 10.0}}
  ignore_index: -1
  lr: 1.0e-4
  optimizer: AdamW
  optimizer_hparams:
    weight_decay: 0.05
  freeze_backbone: false
  plot_on_val: false

trainer:
  max_epochs: 60
  accumulate_grad_batches: 2

checkpoint_dir: data/models/fraction_kfold{fold}
patience: 8
monitor: val/RMSE
monitor_mode: min
"""


def assign_folds() -> pd.DataFrame:
    stems = discover_quadrats(LABELS_DIR)
    folds_csv = pd.read_csv(ROOT / "data/roofclf/folds.csv").set_index("quadrat")
    rows = []
    for s in stems:
        label = quadrat_label(s)
        base_rate = float(folds_csv.loc[label, "base_rate"]) if label in folds_csv.index else float("inf")
        rows.append({"stem": s, "label": label, "base_rate": base_rate})
    df = pd.DataFrame(rows).sort_values(
        "base_rate", na_position="last", kind="stable",
    ).reset_index(drop=True)
    df["fold"] = df.index % N_FOLDS
    return df


def national_chip_bbox_frame(index: pd.DataFrame) -> gpd.GeoDataFrame:
    from shapely.geometry import box

    boxes = [box(*_chip_bbox(r.lon, r.lat)) for r in index.itertuples()]
    return gpd.GeoDataFrame(index.reset_index(drop=True), geometry=boxes, crs=4326)


def main() -> None:
    assignment = assign_folds()
    print(assignment.to_string(index=False))

    germany = pd.read_parquet(CHIPS_DIR / "germany_fraction" / "index.parquet")
    national = pd.read_parquet(CHIPS_DIR / "pakistan_fraction" / "index.parquet")
    quadrat_all = pd.read_parquet(CHIPS_DIR / "pakistan_quadrat_fraction" / "index.parquet")
    national_gdf = national_chip_bbox_frame(national)

    manifest = {}
    for fold in range(N_FOLDS):
        heldout = assignment[assignment.fold == fold]
        heldout_stems = heldout.stem.tolist()
        heldout_labels = ", ".join(heldout.label.tolist())

        boundaries = [load_boundary(LABELS_DIR / f"{s}_boundary.geojson") for s in heldout_stems]
        from shapely.ops import unary_union
        heldout_union = unary_union(boundaries)

        overlapping = national_gdf[national_gdf.intersects(heldout_union)]
        national_fold = national[~national.index.isin(overlapping.index)]
        print(f"fold {fold}: national {len(national)} -> {len(national_fold)} "
              f"({len(overlapping)} chips dropped, overlap held-out: {heldout_labels})")

        quadrat_fold = quadrat_all[~quadrat_all["quadrat"].isin(heldout_stems)]
        train_labels = sorted(set(quadrat_fold["quadrat"].map(quadrat_label)))

        frames = (
            [germany] * GERMANY_REPEAT
            + [national_fold] * PAKISTAN_REPEAT
            + [quadrat_fold] * QUADRAT_REPEAT
        )
        combined = pd.concat(frames, ignore_index=True)
        out_dir = FOLD_DIR / f"fold{fold}"
        out_dir.mkdir(parents=True, exist_ok=True)
        combined.to_parquet(out_dir / "index.parquet")
        print(f"  wrote {out_dir / 'index.parquet'} ({len(combined)} chips: "
              f"germany {len(germany)}x{GERMANY_REPEAT}, national {len(national_fold)}x{PAKISTAN_REPEAT}, "
              f"quadrat {len(quadrat_fold)}x{QUADRAT_REPEAT})")

        config_path = CONFIG_DIR / f"terramind_pv_fraction_kfold{fold}.yaml"
        config_path.write_text(CONFIG_TEMPLATE.format(
            fold=fold, n_heldout=len(heldout_stems), heldout_labels=heldout_labels,
        ))
        print(f"  wrote {config_path}")

        manifest[f"fold{fold}"] = {
            "heldout_stems": heldout_stems, "heldout_labels": heldout.label.tolist(),
            "train_labels": train_labels, "n_national_dropped": int(len(overlapping)),
        }

    manifest_path = FOLD_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"-> {manifest_path}")


if __name__ == "__main__":
    main()
